#!/usr/bin/python

import os, sys

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage:\n\tbilibiliUpSiteDown <numberIdOfaUp>")
        exit(0)

    upId = sys.argv[1]

    if os.path.exists(upId + ".txt"):
        os.remove(upId + ".txt")
    outfile = open(upId + ".txt", "w+")
    out = []

    chrome_options = Options()
    chrome_options.add_argument("--disable-extensions")
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--no-sandbox") # linux only
    chrome_options.add_argument("--headless")

    for i in range(1, 9999):
        with webdriver.Chrome(options=chrome_options) as driver:
            wait = WebDriverWait(driver, 10)
            driver.get("https://space.bilibili.com/" + upId + "/video?tid=0&page=" + str(i) + "&keyword=&order=pubdate")
            spans = driver.find_elements(By.TAG_NAME, "span")
            for span in spans:
                if span.get_attribute("class") is not None and span.get_attribute("class") == "count":
                    if span.text == "0":
                        print("Finished")
                        exit(0)
            tags = driver.find_elements(By.TAG_NAME, "a")
            for tag in tags:
                if tag.get_attribute("class") is not None and tag.get_attribute("class") == "title":
                    out.append(tag.get_attribute("href"))
                    while True:
                        res = os.system("you-get -l \"" + tag.get_attribute("href") + "\" -o Contents")
                        if res == 0:
                            break
                    print("Downloaded " + tag.get_attribute("title"))
                    outfile.write(tag.get_attribute("href") + "\n")
            outfile.flush()
            driver.quit()
